// src/app/docs/api-reference/page.tsx
import {
  DocsLayout,
  DocsSection,
  DocsCode,
  DocsLink,
  DocsNote,
  DocsPropTable,
} from "../_components/docs";
import { CodeBlock } from "../_components/code-block";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "API Reference",
};

const anatomyCode = `<Map>
  <MapMarker longitude={...} latitude={...}>
    <MarkerContent>
      <MarkerLabel />
    </MarkerContent>
    <MarkerPopup />
    <MarkerTooltip />
  </MapMarker>

  <MapPopup longitude={...} latitude={...} />
  <MapControls />
  <MapRoute coordinates={...} />
  <MapClusterLayer data={...} />
</Map>`;

const useMapCode = `const { map, isLoaded } = useMap();`;

export default function ApiReferencePage() {
  return (
    <DocsLayout
      title="API Reference"
      description="Complete reference for all map components and their props."
      prev={{ title: "Installation", href: "/docs/installation" }}
      next={{ title: "Basic Map", href: "/docs/basic-map" }}
    >
      <DocsNote>
        <strong>Note:</strong> This library is built on top of{" "}
        <DocsLink href="https://maplibre.org/maplibre-gl-js/docs/API/" external>
          MapLibre GL JS
        </DocsLink>
        . Most components extend the native MapLibre options. Refer to the{" "}
        <DocsLink
          href="https://maplibre.org/maplibre-gl-js/docs/API/classes/Map/"
          external
        >
          MapLibre Map API
        </DocsLink>{" "}
        for additional options not listed here.
      </DocsNote>

      <DocsSection title="Component Anatomy">
        <p>
          All parts of the component that you can use and combine to build your
          map.
        </p>
        <CodeBlock code={anatomyCode} showCopyButton={false} />
      </DocsSection>

      {/* Map */}
      <DocsSection title="Map">
        <p>
          The root container component that initializes MapLibre GL and provides
          context to child components. Automatically handles theme switching
          between light and dark modes.
        </p>
        <p>
          Extends{" "}
          <DocsLink
            href="https://maplibre.org/maplibre-gl-js/docs/API/type-aliases/MapOptions/"
            external
          >
            MapOptions
          </DocsLink>{" "}
          from MapLibre GL (excluding <DocsCode>container</DocsCode> and{" "}
          <DocsCode>style</DocsCode>).
        </p>
        <DocsPropTable
          props={[
            {
              name: "children",
              type: "ReactNode",
              description:
                "Child components (markers, popups, controls, routes).",
            },
            {
              name: "styles",
              type: "{ light?: string | StyleSpecification; dark?: string | StyleSpecification }",
              description:
                "Custom map styles for light and dark themes. Overrides the default Carto base map tiles.",
            },
          ]}
        />
      </DocsSection>

      {/* useMap */}
      <DocsSection title="useMap">
        <p>
          A hook that provides access to the MapLibre map instance and loading
          state. Must be used within a <DocsCode>Map</DocsCode> component.
        </p>
        <CodeBlock code={useMapCode} language="tsx" showCopyButton={false} />
        <p>
          Returns <DocsCode>map</DocsCode> (
          <DocsLink
            href="https://maplibre.org/maplibre-gl-js/docs/API/classes/Map/"
            external
          >
            MapLibre.Map
          </DocsLink>
          ) and <DocsCode>isLoaded</DocsCode> (boolean) tells you if the map is
          loaded and ready to use.
        </p>
      </DocsSection>

      {/* MapControls */}
      <DocsSection title="MapControls">
        <p>
          Renders map control buttons (zoom, compass, locate, fullscreen). Must
          be used inside <DocsCode>Map</DocsCode>.
        </p>
        <DocsPropTable
          props={[
            {
              name: "position",
              type: '"top-left" | "top-right" | "bottom-left" | "bottom-right"',
              default: '"bottom-right"',
              description: "Position of the controls on the map.",
            },
            {
              name: "showZoom",
              type: "boolean",
              default: "true",
              description: "Show zoom in/out buttons.",
            },
            {
              name: "showCompass",
              type: "boolean",
              default: "false",
              description: "Show compass button to reset bearing.",
            },
            {
              name: "showLocate",
              type: "boolean",
              default: "false",
              description: "Show locate button to find user's location.",
            },
            {
              name: "showFullscreen",
              type: "boolean",
              default: "false",
              description: "Show fullscreen toggle button.",
            },
            {
              name: "className",
              type: "string",
              description: "Additional CSS classes for the controls container.",
            },
            {
              name: "onLocate",
              type: "(coords: { longitude: number; latitude: number }) => void",
              description: "Callback with user coordinates when located.",
            },
          ]}
        />
      </DocsSection>

      {/* MapMarker */}
      <DocsSection title="MapMarker">
        <p>
          A container for marker-related components. Provides context for its
          children and handles marker positioning.
        </p>
        <p>
          Extends{" "}
          <DocsLink
            href="https://maplibre.org/maplibre-gl-js/docs/API/type-aliases/MarkerOptions/"
            external
          >
            MarkerOptions
          </DocsLink>{" "}
          from MapLibre GL (excluding <DocsCode>element</DocsCode>).
        </p>
        <DocsPropTable
          props={[
            {
              name: "longitude",
              type: "number",
              description: "Longitude coordinate for marker position.",
            },
            {
              name: "latitude",
              type: "number",
              description: "Latitude coordinate for marker position.",
            },
            {
              name: "children",
              type: "ReactNode",
              description:
                "Marker subcomponents (MarkerContent, MarkerPopup, etc).",
            },
            {
              name: "onClick",
              type: "(e: MouseEvent) => void",
              description: "Callback when marker is clicked.",
            },
            {
              name: "onMouseEnter",
              type: "(e: MouseEvent) => void",
              description: "Callback when mouse enters marker.",
            },
            {
              name: "onMouseLeave",
              type: "(e: MouseEvent) => void",
              description: "Callback when mouse leaves marker.",
            },
            {
              name: "onDragStart",
              type: "(lngLat: {lng, lat}) => void",
              description:
                "Callback when marker drag starts (requires draggable: true).",
            },
            {
              name: "onDrag",
              type: "(lngLat: {lng, lat}) => void",
              description:
                "Callback during marker drag (requires draggable: true).",
            },
            {
              name: "onDragEnd",
              type: "(lngLat: {lng, lat}) => void",
              description:
                "Callback when marker drag ends (requires draggable: true).",
            },
          ]}
        />
      </DocsSection>

      {/* MarkerContent */}
      <DocsSection title="MarkerContent">
        <p>
          Renders the visual content of a marker. Must be used inside{" "}
          <DocsCode>MapMarker</DocsCode>. If no children provided, renders a
          default blue dot marker.
        </p>
        <DocsPropTable
          props={[
            {
              name: "children",
              type: "ReactNode",
              description: "Custom marker content. Defaults to a blue dot.",
            },
            {
              name: "className",
              type: "string",
              description: "Additional CSS classes for the marker container.",
            },
          ]}
        />
      </DocsSection>

      {/* MarkerPopup */}
      <DocsSection title="MarkerPopup">
        <p>
          Renders a popup attached to the marker that opens on click. Must be
          used inside <DocsCode>MapMarker</DocsCode>.
        </p>
        <p>
          Extends{" "}
          <DocsLink
            href="https://maplibre.org/maplibre-gl-js/docs/API/type-aliases/PopupOptions/"
            external
          >
            PopupOptions
          </DocsLink>{" "}
          from MapLibre GL (excluding <DocsCode>className</DocsCode> and{" "}
          <DocsCode>closeButton</DocsCode>).
        </p>
        <DocsNote>
          The <DocsCode>className</DocsCode> and{" "}
          <DocsCode>closeButton</DocsCode> from MapLibre&apos;s PopupOptions are
          excluded to prevent style conflicts. Use the component&apos;s own
          props to style the popup. MapLibre&apos;s default popup styles are
          reset via CSS.
        </DocsNote>
        <DocsPropTable
          props={[
            {
              name: "children",
              type: "ReactNode",
              description: "Popup content.",
            },
            {
              name: "className",
              type: "string",
              description: "Additional CSS classes for the popup container.",
            },
            {
              name: "closeButton",
              type: "boolean",
              default: "false",
              description: "Show a close button in the popup.",
            },
          ]}
        />
      </DocsSection>

      {/* MarkerTooltip */}
      <DocsSection title="MarkerTooltip">
        <p>
          Renders a tooltip that appears on hover. Must be used inside{" "}
          <DocsCode>MapMarker</DocsCode>.
        </p>
        <p>
          Extends{" "}
          <DocsLink
            href="https://maplibre.org/maplibre-gl-js/docs/API/type-aliases/PopupOptions/"
            external
          >
            PopupOptions
          </DocsLink>{" "}
          from MapLibre GL (excluding <DocsCode>className</DocsCode>,{" "}
          <DocsCode>closeButton</DocsCode>, and{" "}
          <DocsCode>closeOnClick</DocsCode> as tooltips auto-dismiss on hover
          out).
        </p>
        <DocsNote>
          The <DocsCode>className</DocsCode> from MapLibre&apos;s PopupOptions
          is excluded to prevent style conflicts. Use the component&apos;s own{" "}
          <DocsCode>className</DocsCode> prop to style the tooltip content.
          MapLibre&apos;s default popup styles are reset via CSS.
        </DocsNote>
        <DocsPropTable
          props={[
            {
              name: "children",
              type: "ReactNode",
              description: "Tooltip content.",
            },
            {
              name: "className",
              type: "string",
              description: "Additional CSS classes for the tooltip container.",
            },
          ]}
        />
      </DocsSection>

      {/* MarkerLabel */}
      <DocsSection title="MarkerLabel">
        <p>
          Renders a text label above or below the marker. Must be used inside{" "}
          <DocsCode>MarkerContent</DocsCode>.
        </p>
        <DocsPropTable
          props={[
            {
              name: "children",
              type: "ReactNode",
              description: "Label text content.",
            },
            {
              name: "className",
              type: "string",
              description: "Additional CSS classes for the label.",
            },
            {
              name: "position",
              type: '"top" | "bottom"',
              default: '"top"',
              description: "Position of the label relative to the marker.",
            },
          ]}
        />
      </DocsSection>

      {/* MapPopup */}
      <DocsSection title="MapPopup">
        <p>
          A standalone popup component that can be placed anywhere on the map
          without a marker. Must be used inside <DocsCode>Map</DocsCode>.
        </p>
        <p>
          Extends{" "}
          <DocsLink
            href="https://maplibre.org/maplibre-gl-js/docs/API/type-aliases/PopupOptions/"
            external
          >
            PopupOptions
          </DocsLink>{" "}
          from MapLibre GL (excluding <DocsCode>className</DocsCode> and{" "}
          <DocsCode>closeButton</DocsCode>).
        </p>
        <DocsNote>
          The <DocsCode>className</DocsCode> and{" "}
          <DocsCode>closeButton</DocsCode> from MapLibre&apos;s PopupOptions are
          excluded to prevent style conflicts. Use the component&apos;s own
          props to style the popup. MapLibre&apos;s default popup styles are
          reset via CSS.
        </DocsNote>
        <DocsPropTable
          props={[
            {
              name: "longitude",
              type: "number",
              description: "Longitude coordinate for popup position.",
            },
            {
              name: "latitude",
              type: "number",
              description: "Latitude coordinate for popup position.",
            },
            {
              name: "onClose",
              type: "() => void",
              description: "Callback when popup is closed.",
            },
            {
              name: "children",
              type: "ReactNode",
              description: "Popup content.",
            },
            {
              name: "className",
              type: "string",
              description: "Additional CSS classes for the popup container.",
            },
            {
              name: "closeButton",
              type: "boolean",
              default: "false",
              description: "Show a close button in the popup.",
            },
          ]}
        />
      </DocsSection>

      {/* MapRoute */}
      <DocsSection title="MapRoute">
        <p>
          Renders a line/route on the map connecting coordinate points. Must be
          used inside <DocsCode>Map</DocsCode>. Supports click and hover
          interactions for building route selection UIs.
        </p>
        <DocsPropTable
          props={[
            {
              name: "coordinates",
              type: "[number, number][]",
              description: "Array of [longitude, latitude] coordinate pairs.",
            },
            {
              name: "color",
              type: "string",
              default: '"#4285F4"',
              description: "Line color (CSS color value).",
            },
            {
              name: "width",
              type: "number",
              default: "3",
              description: "Line width in pixels.",
            },
            {
              name: "opacity",
              type: "number",
              default: "0.8",
              description: "Line opacity (0 to 1).",
            },
            {
              name: "dashArray",
              type: "[number, number]",
              description:
                "Dash pattern [dash length, gap length] for dashed lines.",
            },
            {
              name: "onClick",
              type: "() => void",
              description: "Callback when the route line is clicked.",
            },
            {
              name: "onMouseEnter",
              type: "() => void",
              description: "Callback when mouse enters the route line.",
            },
            {
              name: "onMouseLeave",
              type: "() => void",
              description: "Callback when mouse leaves the route line.",
            },
            {
              name: "interactive",
              type: "boolean",
              default: "true",
              description:
                "Whether the route is interactive (shows pointer cursor on hover).",
            },
          ]}
        />
      </DocsSection>

      {/* MapClusterLayer */}
      <DocsSection title="MapClusterLayer">
        <p>
          Renders clustered point data using MapLibre GL&apos;s native
          clustering. Automatically groups nearby points into clusters that
          expand on click. Must be used inside <DocsCode>Map</DocsCode>.
          Supports a generic type parameter for typed feature properties:{" "}
          <DocsCode>{"MapClusterLayer<MyProperties>"}</DocsCode>.
        </p>
        <DocsPropTable
          props={[
            {
              name: "data",
              type: "string | GeoJSON.FeatureCollection",
              description:
                "GeoJSON FeatureCollection data or URL to fetch GeoJSON from.",
            },
            {
              name: "clusterMaxZoom",
              type: "number",
              default: "14",
              description: "Maximum zoom level to cluster points on.",
            },
            {
              name: "clusterRadius",
              type: "number",
              default: "50",
              description:
                "Radius of each cluster when clustering points (in pixels).",
            },
            {
              name: "clusterColors",
              type: "[string, string, string]",
              default: '["#51bbd6", "#f1f075", "#f28cb1"]',
              description:
                "Colors for cluster circles: [small, medium, large] based on point count.",
            },
            {
              name: "clusterThresholds",
              type: "[number, number]",
              default: "[100, 750]",
              description:
                "Point count thresholds for color/size steps: [medium, large].",
            },
            {
              name: "pointColor",
              type: "string",
              default: '"#3b82f6"',
              description: "Color for unclustered individual points.",
            },
            {
              name: "onPointClick",
              type: "(feature: GeoJSON.Feature, coordinates: [number, number]) => void",
              description: "Callback when an unclustered point is clicked.",
            },
            {
              name: "onClusterClick",
              type: "(clusterId: number, coordinates: [number, number], pointCount: number) => void",
              description:
                "Callback when a cluster is clicked. If not provided, zooms into the cluster.",
            },
          ]}
        />
      </DocsSection>
    </DocsLayout>
  );
}

// app/pages/docs/api-reference.vue
<script setup lang="ts">
import DocsLayout from '~/components/docs/DocsLayout.vue'
import DocsSection from '~/components/docs/DocsSection.vue'
import DocsCode from '~/components/docs/DocsCode.vue'
import CodeBlock from '~/components/docs/CodeBlock.vue'
import DocsPropTable from '~/components/docs/DocsPropTable.vue'

definePageMeta({ layout: 'docs' })
useSeoMeta({ title: 'API Reference - mapcn-vue' })

const anatomyCode = `<Map>
  <MapMarker :longitude="..." :latitude="...">
    <MarkerContent>
      <!-- Your custom marker content -->
    </MarkerContent>
    <MarkerPopup />
    <MarkerTooltip />
  </MapMarker>

  <MapPopup :longitude="..." :latitude="..." />
  <MapControls :show-compass="true" :show-locate="true" />
  <MapRoute :coordinates="..." color="#3b82f6" />
  <MapClusterLayer :data="..." />
</Map>`

const useMapCode = `const { map, isLoaded, isStyleLoaded } = useMap()`
</script>

<template>
  <DocsLayout
    title="API Reference"
    description="Complete reference for all map components and their props."
    :prev="{ title: 'Installation', href: '/docs/installation' }"
    :next="{ title: 'Map', href: '/docs/basic-map' }"
    :toc="[
      { title: 'Component Anatomy', slug: 'component-anatomy' },
      { title: 'Map', slug: 'map' },
      { title: 'useMap', slug: 'usemap' },
      { title: 'MapControls', slug: 'mapcontrols' },
      { title: 'MapMarker', slug: 'mapmarker' },
      { title: 'MarkerContent', slug: 'markercontent' },
      { title: 'MarkerLabel', slug: 'markerlabel' },
      { title: 'MarkerPopup', slug: 'markerpopup' },
      { title: 'MarkerTooltip', slug: 'markertooltip' },
      { title: 'MapPopup', slug: 'mappopup' },
      { title: 'MapRoute', slug: 'maproute' },
      { title: 'MapClusterLayer', slug: 'mapclusterlayer' },
    ]"
  >
    <DocsNote>
      <strong>Note:</strong> This library is built on top of
      <DocsLink href="https://maplibre.org/maplibre-gl-js/docs/API/" external>
        MapLibre GL JS
      </DocsLink>. Most components extend the native MapLibre options.
    </DocsNote>

    <DocsSection title="Component Anatomy">
      <p>
        All parts of the component that you can use and combine to build your
        map.
      </p>
      <CodeBlock :code="anatomyCode" :show-copy-button="false" />
    </DocsSection>

    <DocsSection title="Map">
      <p>
        The root container component that initializes MapLibre GL and provides
        context to child components. Automatically handles theme switching
        between light and dark modes.
      </p>
      <DocsPropTable
        :props="[
          { name: 'center', type: '[number, number]', description: 'Initial center coordinates [longitude, latitude]' },
          { name: 'zoom', type: 'number', default: '10', description: 'Initial zoom level' },
          { name: 'theme', type: '\'light\' | \'dark\'', description: 'Map theme (auto-detected if not provided)' },
          { name: 'viewport', type: 'Partial&lt;MapViewport&gt;', description: 'Controlled viewport state with center, zoom, bearing, pitch' },
          { name: 'onViewportChange', type: '(viewport: MapViewport) =&gt; void', description: 'Callback when viewport changes (for controlled mode)' },
          { name: 'projection', type: 'ProjectionSpecification', description: 'Map projection (e.g., { type: \'globe\' })' },
          { name: 'styles', type: '{ light?: string, dark?: string }', description: 'Custom map styles for light/dark themes' },
        ]"
      />
    </DocsSection>

    <DocsSection title="useMap">
      <p>
        A composable that provides access to the MapLibre map instance and loading
        state. Must be used within a <DocsCode>Map</DocsCode> component.
      </p>
      <CodeBlock :code="useMapCode" language="ts" :show-copy-button="false" />
      <p class="mt-4">
        Returns an object with:
      </p>
      <ul class="mt-2 space-y-1 list-disc list-inside">
        <li><DocsCode>map</DocsCode> - The MapLibre GL map instance (ref)</li>
        <li><DocsCode>isLoaded</DocsCode> - Boolean indicating if the map is loaded</li>
        <li><DocsCode>isStyleLoaded</DocsCode> - Boolean indicating if the map style is loaded</li>
      </ul>
    </DocsSection>

    <DocsSection title="MapControls">
      <p>
        Renders map control buttons (zoom, compass, locate, fullscreen). Must
        be used inside <DocsCode>Map</DocsCode>. The compass automatically rotates
        to match the map's bearing.
      </p>
      <DocsPropTable
        :props="[
          { name: 'position', type: '\'top-left\' | \'top-right\' | \'bottom-left\' | \'bottom-right\'', default: '\'bottom-right\'', description: 'Position of the controls' },
          { name: 'showZoom', type: 'boolean', default: 'true', description: 'Show zoom in/out buttons' },
          { name: 'showCompass', type: 'boolean', default: 'false', description: 'Show compass button that rotates with map bearing' },
          { name: 'showLocate', type: 'boolean', default: 'false', description: 'Show locate button to find user location' },
          { name: 'showFullscreen', type: 'boolean', default: 'false', description: 'Show fullscreen toggle button' },
          { name: 'onLocate', type: '(coords: { longitude: number; latitude: number }) =&gt; void', description: 'Callback when user location is found' },
        ]"
      />
    </DocsSection>

    <DocsSection title="MapMarker">
      <p>
        Renders a customizable marker on the map. Supports drag events and provides
        context for MarkerPopup and MarkerTooltip components.
      </p>
      <DocsPropTable
        :props="[
          { name: 'longitude', type: 'number', description: 'Longitude coordinate (required)' },
          { name: 'latitude', type: 'number', description: 'Latitude coordinate (required)' },
          { name: 'draggable', type: 'boolean', default: 'false', description: 'Whether the marker is draggable' },
          { name: 'onDragStart', type: '(lngLat: { lng: number; lat: number }) =&gt; void', description: 'Callback when drag starts' },
          { name: 'onDrag', type: '(lngLat: { lng: number; lat: number }) =&gt; void', description: 'Callback during drag' },
          { name: 'onDragEnd', type: '(lngLat: { lng: number; lat: number }) =&gt; void', description: 'Callback when drag ends' },
          { name: 'onClick', type: '(e: MouseEvent) =&gt; void', description: 'Callback when marker is clicked' },
          { name: 'onMouseEnter', type: '(e: MouseEvent) =&gt; void', description: 'Callback when mouse enters marker' },
          { name: 'onMouseLeave', type: '(e: MouseEvent) =&gt; void', description: 'Callback when mouse leaves marker' },
          { name: 'anchor', type: 'string', default: '\'center\'', description: 'The anchor position of the marker' },
          { name: 'offset', type: 'PointLike', description: 'Offset in pixels from the anchor position' },
          { name: 'rotation', type: 'number', default: '0', description: 'Rotation angle in degrees' },
        ]"
      />
    </DocsSection>

    <DocsSection title="MarkerContent">
      <p>
        Renders custom content inside a marker. Must be used inside
        <DocsCode>MapMarker</DocsCode>. If no children are provided, a default
        blue dot marker is rendered.
      </p>
      <DocsPropTable
        :props="[
          { name: 'class', type: 'string', description: 'Additional CSS classes for the marker container' },
        ]"
      />
    </DocsSection>

    <DocsSection title="MarkerLabel">
      <p>
        Renders a text label positioned above or below a marker. Must be used inside
        <DocsCode>MarkerContent</DocsCode>.
      </p>
      <DocsPropTable
        :props="[
          { name: 'position', type: '\'top\' | \'bottom\'', default: '\'top\'', description: 'Position of the label relative to the marker' },
          { name: 'class', type: 'string', description: 'Additional CSS classes for the label' },
        ]"
      />
    </DocsSection>

    <DocsSection title="MarkerPopup">
      <p>
        Displays a popup when the marker is clicked. Must be used inside MapMarker.
        The popup content is fully customizable using the default slot.
      </p>
      <DocsPropTable
        :props="[
          { name: 'offset', type: 'number', default: '16', description: 'Popup offset from marker in pixels' },
          { name: 'closeButton', type: 'boolean', default: 'false', description: 'Show close button in popup' },
          { name: 'closeOnClick', type: 'boolean', default: 'true', description: 'Close popup when clicking elsewhere' },
          { name: 'anchor', type: '\'top\' | \'bottom\' | \'left\' | \'right\' | \'center\' | \'top-left\' | \'top-right\' | \'bottom-left\' | \'bottom-right\'', description: 'Popup anchor position' },
        ]"
      />
    </DocsSection>

    <DocsSection title="MarkerTooltip">
      <p>
        Displays a tooltip on hover. Must be used inside MapMarker.
        Perfect for showing brief information without clicking.
      </p>
      <DocsPropTable
        :props="[
          { name: 'offset', type: 'number', default: '16', description: 'Tooltip offset from marker in pixels' },
          { name: 'anchor', type: '\'top\' | \'bottom\' | \'left\' | \'right\' | \'center\' | \'top-left\' | \'top-right\' | \'bottom-left\' | \'bottom-right\'', description: 'Tooltip anchor position' },
        ]"
      />
    </DocsSection>

    <DocsSection title="MapPopup">
      <p>
        A standalone popup that can be placed anywhere on the map using coordinates.
        Unlike MarkerPopup, this is not tied to a marker.
      </p>
      <DocsPropTable
        :props="[
          { name: 'longitude', type: 'number', description: 'Longitude coordinate (required)' },
          { name: 'latitude', type: 'number', description: 'Latitude coordinate (required)' },
          { name: 'offset', type: 'number', default: '16', description: 'Popup offset from coordinates in pixels' },
          { name: 'closeButton', type: 'boolean', default: 'false', description: 'Show close button' },
          { name: 'closeOnClick', type: 'boolean', default: 'true', description: 'Close when clicking elsewhere' },
          { name: 'onClose', type: '() =&gt; void', description: 'Callback when popup closes' },
        ]"
      />
    </DocsSection>

    <DocsSection title="MapRoute">
      <p>
        Renders a line/route on the map connecting coordinate points.
        Supports animation and automatic bounds fitting.
      </p>
      <DocsPropTable
        :props="[
          { name: 'coordinates', type: '[number, number][]', description: 'Array of [longitude, latitude] pairs (required)' },
          { name: 'color', type: 'string', default: '\'#4285F4\'', description: 'Line color' },
          { name: 'width', type: 'number', default: '3', description: 'Line width in pixels' },
          { name: 'opacity', type: 'number', default: '0.8', description: 'Line opacity (0-1)' },
          { name: 'dashArray', type: '[number, number]', description: 'Dash pattern [dash length, gap length]' },
          { name: 'animated', type: 'boolean', default: 'false', description: 'Animate the route drawing' },
          { name: 'animationDuration', type: 'number', default: '2000', description: 'Animation duration in milliseconds' },
          { name: 'fitBounds', type: 'boolean', default: 'false', description: 'Automatically zoom to fit the route' },
          { name: 'fitBoundsOptions', type: 'FitBoundsOptions', description: 'Options for fitBounds (padding, etc)' },
          { name: 'interactive', type: 'boolean', default: 'true', description: 'Enable hover/click interactions' },
          { name: 'onClick', type: '() =&gt; void', description: 'Callback when route is clicked' },
        ]"
      />
    </DocsSection>

    <DocsSection title="MapClusterLayer">
      <p>
        Renders clustered point data using MapLibre GL's native clustering.
        Points are automatically grouped at low zoom levels and expand as you zoom in.
      </p>
      <DocsPropTable
        :props="[
          { name: 'data', type: 'string | GeoJSON.FeatureCollection&lt;GeoJSON.Point&gt;', description: 'GeoJSON data or URL (required)' },
          { name: 'clusterMaxZoom', type: 'number', default: '14', description: 'Maximum zoom level to cluster points' },
          { name: 'clusterRadius', type: 'number', default: '50', description: 'Cluster radius in pixels' },
          { name: 'clusterColors', type: '[string, string, string]', default: '[\'#22c55e\', \'#eab308\', \'#ef4444\']', description: 'Colors for different cluster sizes' },
          { name: 'clusterThresholds', type: '[number, number]', default: '[100, 750]', description: 'Point count thresholds for cluster colors' },
          { name: 'pointColor', type: 'string', default: '\'#3b82f6\'', description: 'Color for individual (unclustered) points' },
          { name: 'onPointClick', type: '(feature: GeoJSON.Feature, coordinates: [number, number]) =&gt; void', description: 'Callback when a point is clicked' },
          { name: 'onClusterClick', type: '(clusterId: number, coordinates: [number, number], pointCount: number) =&gt; void', description: 'Callback when a cluster is clicked' },
        ]"
      />
    </DocsSection>
  </DocsLayout>
</template>
